#############################################################################
# Makefile for building: BuksanSpy
# Generated by qmake (3.1) (Qt 6.9.1)
# Project:  BuksanSpy.pro
# Template: app
# Command: /usr/bin/qmake6 -o Makefile BuksanSpy.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_NO_DEBUG -DQT_MULTIMEDIA_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O2 -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -std=gnu++1z -Wall -Wextra -mno-direct-extern-access -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I. -I. -I/usr/lib/qt6/mkspecs/linux-g++
QMAKE         = /usr/bin/qmake6
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/bin/qmake6 -install qinstall
QINSTALL_PROGRAM = /usr/bin/qmake6 -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = BuksanSpy1.0.0
DISTDIR = /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/.tmp/BuksanSpy1.0.0
LINK          = g++
LFLAGS        = -Wl,-O1 -Wl,-rpath,/usr/lib -Wl,-rpath-link,/usr/lib
LIBS          = $(SUBLIBS) -lopencv_core -lopencv_imgproc -lopencv_videoio -lopencv_imgcodecs /usr/lib/libQt6Multimedia.so /usr/lib/libQt6Widgets.so /usr/lib/libQt6Gui.so /usr/lib/libGLX.so /usr/lib/libOpenGL.so /usr/lib/libQt6Sql.so /usr/lib/libQt6Network.so /usr/lib/libQt6Core.so -lpthread -lGLX -lOpenGL   
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = accessmanager.cpp \
		adddevice.cpp \
		authorization.cpp \
		buksanspyapp.cpp \
		buksanviewfinder.cpp \
		cameravideocapture.cpp \
		checkconnection.cpp \
		checkstring.cpp \
		createuser.cpp \
		databaseconnection.cpp \
		datacryptor.cpp \
		devices.cpp \
		editmandatorygroup.cpp \
		eventlog.cpp \
		main.cpp \
		buksanspy.cpp \
		mandatorygroups.cpp \
		mandatorymarkcreator.cpp \
		mandatorymarkseditor.cpp \
		networkinfo.cpp \
		sendalert.cpp \
		users.cpp moc_accessmanager.cpp \
		moc_adddevice.cpp \
		moc_authorization.cpp \
		moc_buksanspy.cpp \
		moc_buksanviewfinder.cpp \
		moc_cameravideocapture.cpp \
		moc_checkconnection.cpp \
		moc_checkstring.cpp \
		moc_createuser.cpp \
		moc_databaseconnection.cpp \
		moc_datacryptor.cpp \
		moc_devices.cpp \
		moc_editmandatorygroup.cpp \
		moc_eventlog.cpp \
		moc_mandatorygroups.cpp \
		moc_mandatorymarkcreator.cpp \
		moc_mandatorymarkseditor.cpp \
		moc_networkinfo.cpp \
		moc_sendalert.cpp \
		moc_users.cpp
OBJECTS       = accessmanager.o \
		adddevice.o \
		authorization.o \
		buksanspyapp.o \
		buksanviewfinder.o \
		cameravideocapture.o \
		checkconnection.o \
		checkstring.o \
		createuser.o \
		databaseconnection.o \
		datacryptor.o \
		devices.o \
		editmandatorygroup.o \
		eventlog.o \
		main.o \
		buksanspy.o \
		mandatorygroups.o \
		mandatorymarkcreator.o \
		mandatorymarkseditor.o \
		networkinfo.o \
		sendalert.o \
		users.o \
		moc_accessmanager.o \
		moc_adddevice.o \
		moc_authorization.o \
		moc_buksanspy.o \
		moc_buksanviewfinder.o \
		moc_cameravideocapture.o \
		moc_checkconnection.o \
		moc_checkstring.o \
		moc_createuser.o \
		moc_databaseconnection.o \
		moc_datacryptor.o \
		moc_devices.o \
		moc_editmandatorygroup.o \
		moc_eventlog.o \
		moc_mandatorygroups.o \
		moc_mandatorymarkcreator.o \
		moc_mandatorymarkseditor.o \
		moc_networkinfo.o \
		moc_sendalert.o \
		moc_users.o
DIST          = /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSingleApplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackWidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_connectivity_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCoro.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroDBus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroNetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQuick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroTest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroWebSockets.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		BuksanSpy.pro accessmanager.h \
		adddevice.h \
		authorization.h \
		buksanspy.h \
		buksanspyapp.h \
		buksanviewfinder.h \
		cameravideocapture.h \
		checkconnection.h \
		checkstring.h \
		createuser.h \
		databaseconnection.h \
		datacryptor.h \
		devices.h \
		editmandatorygroup.h \
		eventlog.h \
		mandatorygroups.h \
		mandatorymarkcreator.h \
		mandatorymarkseditor.h \
		networkinfo.h \
		sendalert.h \
		users.h accessmanager.cpp \
		adddevice.cpp \
		authorization.cpp \
		buksanspyapp.cpp \
		buksanviewfinder.cpp \
		cameravideocapture.cpp \
		checkconnection.cpp \
		checkstring.cpp \
		createuser.cpp \
		databaseconnection.cpp \
		datacryptor.cpp \
		devices.cpp \
		editmandatorygroup.cpp \
		eventlog.cpp \
		main.cpp \
		buksanspy.cpp \
		mandatorygroups.cpp \
		mandatorymarkcreator.cpp \
		mandatorymarkseditor.cpp \
		networkinfo.cpp \
		sendalert.cpp \
		users.cpp
QMAKE_TARGET  = BuksanSpy
DESTDIR       = 
TARGET        = BuksanSpy


first: all
####### Build rules

BuksanSpy: ui_adddevice.h ui_authorization.h ui_buksanspy.h ui_createuser.h ui_devices.h ui_editmandatorygroup.h ui_eventlog.h ui_mandatorygroups.h ui_mandatorymarkcreator.h ui_mandatorymarkseditor.h ui_users.h $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET)  $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: BuksanSpy.pro /usr/lib/qt6/mkspecs/linux-g++/qmake.conf /usr/lib/qt6/mkspecs/features/spec_pre.prf \
		/usr/lib/qt6/mkspecs/common/unix.conf \
		/usr/lib/qt6/mkspecs/common/linux.conf \
		/usr/lib/qt6/mkspecs/common/sanitize.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base.conf \
		/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/qt6/mkspecs/common/g++-base.conf \
		/usr/lib/qt6/mkspecs/common/g++-unix.conf \
		/usr/lib/qt6/mkspecs/qconfig.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSingleApplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapClient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KDSoapServer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackWidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_connectivity_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_location.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_location_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_nfc_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webview_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCore.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroCoro.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroDBus.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroNetwork.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQml.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroQuick.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroTest.pri \
		/usr/lib/qt6/mkspecs/modules/qt_QCoroWebSockets.pri \
		/usr/lib/qt6/mkspecs/features/qt_functions.prf \
		/usr/lib/qt6/mkspecs/features/qt_config.prf \
		/usr/lib/qt6/mkspecs/linux-g++/qmake.conf \
		/usr/lib/qt6/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/qt6/mkspecs/features/exclusive_builds.prf \
		/usr/lib/qt6/mkspecs/features/toolchain.prf \
		/usr/lib/qt6/mkspecs/features/default_pre.prf \
		/usr/lib/qt6/mkspecs/features/resolve_config.prf \
		/usr/lib/qt6/mkspecs/features/default_post.prf \
		/usr/lib/qt6/mkspecs/features/warn_on.prf \
		/usr/lib/qt6/mkspecs/features/permissions.prf \
		/usr/lib/qt6/mkspecs/features/qt.prf \
		/usr/lib/qt6/mkspecs/features/resources_functions.prf \
		/usr/lib/qt6/mkspecs/features/resources.prf \
		/usr/lib/qt6/mkspecs/features/moc.prf \
		/usr/lib/qt6/mkspecs/features/link_ltcg.prf \
		/usr/lib/qt6/mkspecs/features/unix/opengl.prf \
		/usr/lib/qt6/mkspecs/features/uic.prf \
		/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf \
		/usr/lib/qt6/mkspecs/features/unix/thread.prf \
		/usr/lib/qt6/mkspecs/features/qmake_use.prf \
		/usr/lib/qt6/mkspecs/features/file_copies.prf \
		/usr/lib/qt6/mkspecs/features/testcase_targets.prf \
		/usr/lib/qt6/mkspecs/features/exceptions.prf \
		/usr/lib/qt6/mkspecs/features/yacc.prf \
		/usr/lib/qt6/mkspecs/features/lex.prf \
		BuksanSpy.pro \
		/usr/lib/libQt6Multimedia.prl \
		/usr/lib/libQt6Widgets.prl \
		/usr/lib/libQt6Gui.prl \
		/usr/lib/libQt6Sql.prl \
		/usr/lib/libQt6Network.prl \
		/usr/lib/libQt6Core.prl
	$(QMAKE) -o Makefile BuksanSpy.pro
/usr/lib/qt6/mkspecs/features/spec_pre.prf:
/usr/lib/qt6/mkspecs/common/unix.conf:
/usr/lib/qt6/mkspecs/common/linux.conf:
/usr/lib/qt6/mkspecs/common/sanitize.conf:
/usr/lib/qt6/mkspecs/common/gcc-base.conf:
/usr/lib/qt6/mkspecs/common/gcc-base-unix.conf:
/usr/lib/qt6/mkspecs/common/g++-base.conf:
/usr/lib/qt6/mkspecs/common/g++-unix.conf:
/usr/lib/qt6/mkspecs/qconfig.pri:
/usr/lib/qt6/mkspecs/modules/qt_KDSingleApplication.pri:
/usr/lib/qt6/mkspecs/modules/qt_KDSoapClient.pri:
/usr/lib/qt6/mkspecs/modules/qt_KDSoapServer.pri:
/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackCore.pri:
/usr/lib/qt6/mkspecs/modules/qt_KF6UserFeedbackWidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_bluetooth_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_connectivity_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core5compat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designer_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_designercomponents_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_gbm_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_example_icons_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_examples_asset_downloader_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_ffmpegmediapluginimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_help_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_hunspellinputmethod_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsanimation_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsfolderlistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsplatform_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labsqmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labssharedimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_labswavefrontmesh_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_linguist.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_location.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_location_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimedia_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediaquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediatestlibprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_networkauth_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_nfc.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_nfc_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_openglwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_packetprotocol_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdf_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_pdfwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioning_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_positioningquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatch_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchconversions_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qdoccatchgenerators_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlassetdownloader_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcompiler_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlcore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldebug_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmldom_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlformat_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlintegration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmllocalstorage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlls_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmeta_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlmodels_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlnetwork_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltest_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltoolingsettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmltyperegistrar_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlworkerscript_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_qmlxmllistmodel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3d_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetimport_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dassetutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3deffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dglslparser_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpers_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dhelpersimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3diblbaker_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticleeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3druntimerender_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dspatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dutils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick3dxr_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basic_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2basicstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fluentwinui3styleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusion_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2fusionstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imagine_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2imaginestyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2impl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2material_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2materialstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrols2universalstyleimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickcontrolstestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2quickimpl_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickdialogs2utils_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickeffects_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicklayouts_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickparticles_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickshapes_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktemplates2_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktestutilsprivate_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimeline_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quicktimelineblendtrees_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimage_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickvectorimagegenerator_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensors.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensors_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sensorsquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_shadertools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_spatialaudio_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svg_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_svgwidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testinternals_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_texttospeech_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_tools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uiplugin.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_uitools_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboard_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_virtualkeyboardsettings_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_client_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wayland_egl_compositor_hw_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandclient_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositor_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositoriviapplication_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorpresentationtime_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorwlshell_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandcompositorxdgshell_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_waylandglobal_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannel_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webchannelquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginecore_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginequickdelegatesqml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webenginewidgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_websockets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webview.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webview_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_webviewquick_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_wl_shell_integration_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/qt6/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroCore.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroCoro.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroDBus.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroNetwork.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroQml.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroQuick.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroTest.pri:
/usr/lib/qt6/mkspecs/modules/qt_QCoroWebSockets.pri:
/usr/lib/qt6/mkspecs/features/qt_functions.prf:
/usr/lib/qt6/mkspecs/features/qt_config.prf:
/usr/lib/qt6/mkspecs/linux-g++/qmake.conf:
/usr/lib/qt6/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/qt6/mkspecs/features/exclusive_builds.prf:
/usr/lib/qt6/mkspecs/features/toolchain.prf:
/usr/lib/qt6/mkspecs/features/default_pre.prf:
/usr/lib/qt6/mkspecs/features/resolve_config.prf:
/usr/lib/qt6/mkspecs/features/default_post.prf:
/usr/lib/qt6/mkspecs/features/warn_on.prf:
/usr/lib/qt6/mkspecs/features/permissions.prf:
/usr/lib/qt6/mkspecs/features/qt.prf:
/usr/lib/qt6/mkspecs/features/resources_functions.prf:
/usr/lib/qt6/mkspecs/features/resources.prf:
/usr/lib/qt6/mkspecs/features/moc.prf:
/usr/lib/qt6/mkspecs/features/link_ltcg.prf:
/usr/lib/qt6/mkspecs/features/unix/opengl.prf:
/usr/lib/qt6/mkspecs/features/uic.prf:
/usr/lib/qt6/mkspecs/features/unix/no_direct_extern_access.prf:
/usr/lib/qt6/mkspecs/features/unix/thread.prf:
/usr/lib/qt6/mkspecs/features/qmake_use.prf:
/usr/lib/qt6/mkspecs/features/file_copies.prf:
/usr/lib/qt6/mkspecs/features/testcase_targets.prf:
/usr/lib/qt6/mkspecs/features/exceptions.prf:
/usr/lib/qt6/mkspecs/features/yacc.prf:
/usr/lib/qt6/mkspecs/features/lex.prf:
BuksanSpy.pro:
/usr/lib/libQt6Multimedia.prl:
/usr/lib/libQt6Widgets.prl:
/usr/lib/libQt6Gui.prl:
/usr/lib/libQt6Sql.prl:
/usr/lib/libQt6Network.prl:
/usr/lib/libQt6Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile BuksanSpy.pro

qmake_all: FORCE


all: Makefile BuksanSpy

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /usr/lib/qt6/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents accessmanager.h adddevice.h authorization.h buksanspy.h buksanspyapp.h buksanviewfinder.h cameravideocapture.h checkconnection.h checkstring.h createuser.h databaseconnection.h datacryptor.h devices.h editmandatorygroup.h eventlog.h mandatorygroups.h mandatorymarkcreator.h mandatorymarkseditor.h networkinfo.h sendalert.h users.h $(DISTDIR)/
	$(COPY_FILE) --parents accessmanager.cpp adddevice.cpp authorization.cpp buksanspyapp.cpp buksanviewfinder.cpp cameravideocapture.cpp checkconnection.cpp checkstring.cpp createuser.cpp databaseconnection.cpp datacryptor.cpp devices.cpp editmandatorygroup.cpp eventlog.cpp main.cpp buksanspy.cpp mandatorygroups.cpp mandatorymarkcreator.cpp mandatorymarkseditor.cpp networkinfo.cpp sendalert.cpp users.cpp $(DISTDIR)/
	$(COPY_FILE) --parents adddevice.ui authorization.ui buksanspy.ui createuser.ui devices.ui editmandatorygroup.ui eventlog.ui mandatorygroups.ui mandatorymarkcreator.ui mandatorymarkseditor.ui users.ui $(DISTDIR)/
	$(COPY_FILE) --parents BuksanSpy_ru_RU.ts $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_objc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_objc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /usr/lib/qt6/mkspecs/features/data/dummy.cpp
	g++ -pipe -O2 -std=gnu++1z -Wall -Wextra -dM -E -o moc_predefs.h /usr/lib/qt6/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_accessmanager.cpp moc_adddevice.cpp moc_authorization.cpp moc_buksanspy.cpp moc_buksanviewfinder.cpp moc_cameravideocapture.cpp moc_checkconnection.cpp moc_checkstring.cpp moc_createuser.cpp moc_databaseconnection.cpp moc_datacryptor.cpp moc_devices.cpp moc_editmandatorygroup.cpp moc_eventlog.cpp moc_mandatorygroups.cpp moc_mandatorymarkcreator.cpp moc_mandatorymarkseditor.cpp moc_networkinfo.cpp moc_sendalert.cpp moc_users.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_accessmanager.cpp moc_adddevice.cpp moc_authorization.cpp moc_buksanspy.cpp moc_buksanviewfinder.cpp moc_cameravideocapture.cpp moc_checkconnection.cpp moc_checkstring.cpp moc_createuser.cpp moc_databaseconnection.cpp moc_datacryptor.cpp moc_devices.cpp moc_editmandatorygroup.cpp moc_eventlog.cpp moc_mandatorygroups.cpp moc_mandatorymarkcreator.cpp moc_mandatorymarkseditor.cpp moc_networkinfo.cpp moc_sendalert.cpp moc_users.cpp
moc_accessmanager.cpp: accessmanager.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include accessmanager.h -o moc_accessmanager.cpp

moc_adddevice.cpp: adddevice.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include adddevice.h -o moc_adddevice.cpp

moc_authorization.cpp: authorization.h \
		sendalert.h \
		databaseconnection.h \
		buksanspy.h \
		accessmanager.h \
		users.h \
		createuser.h \
		checkstring.h \
		mandatorygroups.h \
		editmandatorygroup.h \
		checkconnection.h \
		buksanviewfinder.h \
		cameravideocapture.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include authorization.h -o moc_authorization.cpp

moc_buksanspy.cpp: buksanspy.h \
		accessmanager.h \
		users.h \
		createuser.h \
		checkstring.h \
		sendalert.h \
		mandatorygroups.h \
		editmandatorygroup.h \
		checkconnection.h \
		buksanviewfinder.h \
		cameravideocapture.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include buksanspy.h -o moc_buksanspy.cpp

moc_buksanviewfinder.cpp: buksanviewfinder.h \
		cameravideocapture.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include buksanviewfinder.h -o moc_buksanviewfinder.cpp

moc_cameravideocapture.cpp: cameravideocapture.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include cameravideocapture.h -o moc_cameravideocapture.cpp

moc_checkconnection.cpp: checkconnection.h \
		sendalert.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include checkconnection.h -o moc_checkconnection.cpp

moc_checkstring.cpp: checkstring.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include checkstring.h -o moc_checkstring.cpp

moc_createuser.cpp: createuser.h \
		checkstring.h \
		sendalert.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include createuser.h -o moc_createuser.cpp

moc_databaseconnection.cpp: databaseconnection.h \
		sendalert.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include databaseconnection.h -o moc_databaseconnection.cpp

moc_datacryptor.cpp: datacryptor.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include datacryptor.h -o moc_datacryptor.cpp

moc_devices.cpp: devices.h \
		cameravideocapture.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include devices.h -o moc_devices.cpp

moc_editmandatorygroup.cpp: editmandatorygroup.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include editmandatorygroup.h -o moc_editmandatorygroup.cpp

moc_eventlog.cpp: eventlog.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include eventlog.h -o moc_eventlog.cpp

moc_mandatorygroups.cpp: mandatorygroups.h \
		accessmanager.h \
		editmandatorygroup.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include mandatorygroups.h -o moc_mandatorygroups.cpp

moc_mandatorymarkcreator.cpp: mandatorymarkcreator.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include mandatorymarkcreator.h -o moc_mandatorymarkcreator.cpp

moc_mandatorymarkseditor.cpp: mandatorymarkseditor.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include mandatorymarkseditor.h -o moc_mandatorymarkseditor.cpp

moc_networkinfo.cpp: networkinfo.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include networkinfo.h -o moc_networkinfo.cpp

moc_sendalert.cpp: sendalert.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include sendalert.h -o moc_sendalert.cpp

moc_users.cpp: users.h \
		createuser.h \
		checkstring.h \
		sendalert.h \
		accessmanager.h \
		moc_predefs.h \
		/usr/lib/qt6/moc
	/usr/lib/qt6/moc $(DEFINES) --include /home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy/moc_predefs.h -I/usr/lib/qt6/mkspecs/linux-g++ -I/home/mikhail/Documents/QtProjects/BuksanSpy/BuksanSpy -I/usr/include/opencv4 -I/usr/include/qt6 -I/usr/include/qt6/QtMultimedia -I/usr/include/qt6/QtWidgets -I/usr/include/qt6/QtGui -I/usr/include/qt6/QtSql -I/usr/include/qt6/QtNetwork -I/usr/include/qt6/QtCore -I/usr/include/c++/15.1.1 -I/usr/include/c++/15.1.1/x86_64-pc-linux-gnu -I/usr/include/c++/15.1.1/backward -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include -I/usr/local/include -I/usr/lib/gcc/x86_64-pc-linux-gnu/15.1.1/include-fixed -I/usr/include users.h -o moc_users.cpp

compiler_moc_objc_header_make_all:
compiler_moc_objc_header_clean:
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all: ui_adddevice.h ui_authorization.h ui_buksanspy.h ui_createuser.h ui_devices.h ui_editmandatorygroup.h ui_eventlog.h ui_mandatorygroups.h ui_mandatorymarkcreator.h ui_mandatorymarkseditor.h ui_users.h
compiler_uic_clean:
	-$(DEL_FILE) ui_adddevice.h ui_authorization.h ui_buksanspy.h ui_createuser.h ui_devices.h ui_editmandatorygroup.h ui_eventlog.h ui_mandatorygroups.h ui_mandatorymarkcreator.h ui_mandatorymarkseditor.h ui_users.h
ui_adddevice.h: adddevice.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic adddevice.ui -o ui_adddevice.h

ui_authorization.h: authorization.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic authorization.ui -o ui_authorization.h

ui_buksanspy.h: buksanspy.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic buksanspy.ui -o ui_buksanspy.h

ui_createuser.h: createuser.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic createuser.ui -o ui_createuser.h

ui_devices.h: devices.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic devices.ui -o ui_devices.h

ui_editmandatorygroup.h: editmandatorygroup.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic editmandatorygroup.ui -o ui_editmandatorygroup.h

ui_eventlog.h: eventlog.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic eventlog.ui -o ui_eventlog.h

ui_mandatorygroups.h: mandatorygroups.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic mandatorygroups.ui -o ui_mandatorygroups.h

ui_mandatorymarkcreator.h: mandatorymarkcreator.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic mandatorymarkcreator.ui -o ui_mandatorymarkcreator.h

ui_mandatorymarkseditor.h: mandatorymarkseditor.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic mandatorymarkseditor.ui -o ui_mandatorymarkseditor.h

ui_users.h: users.ui \
		/usr/lib/qt6/uic
	/usr/lib/qt6/uic users.ui -o ui_users.h

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean compiler_uic_clean 

####### Compile

accessmanager.o: accessmanager.cpp accessmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o accessmanager.o accessmanager.cpp

adddevice.o: adddevice.cpp adddevice.h \
		ui_adddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o adddevice.o adddevice.cpp

authorization.o: authorization.cpp authorization.h \
		sendalert.h \
		databaseconnection.h \
		buksanspy.h \
		accessmanager.h \
		users.h \
		createuser.h \
		checkstring.h \
		mandatorygroups.h \
		editmandatorygroup.h \
		checkconnection.h \
		buksanviewfinder.h \
		cameravideocapture.h \
		ui_authorization.h \
		datacryptor.h \
		buksanspyapp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o authorization.o authorization.cpp

buksanspyapp.o: buksanspyapp.cpp buksanspyapp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buksanspyapp.o buksanspyapp.cpp

buksanviewfinder.o: buksanviewfinder.cpp buksanviewfinder.h \
		cameravideocapture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buksanviewfinder.o buksanviewfinder.cpp

cameravideocapture.o: cameravideocapture.cpp cameravideocapture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o cameravideocapture.o cameravideocapture.cpp

checkconnection.o: checkconnection.cpp checkconnection.h \
		sendalert.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o checkconnection.o checkconnection.cpp

checkstring.o: checkstring.cpp checkstring.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o checkstring.o checkstring.cpp

createuser.o: createuser.cpp createuser.h \
		checkstring.h \
		sendalert.h \
		ui_createuser.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o createuser.o createuser.cpp

databaseconnection.o: databaseconnection.cpp databaseconnection.h \
		sendalert.h \
		users.h \
		createuser.h \
		checkstring.h \
		accessmanager.h \
		eventlog.h \
		mandatorygroups.h \
		editmandatorygroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o databaseconnection.o databaseconnection.cpp

datacryptor.o: datacryptor.cpp datacryptor.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o datacryptor.o datacryptor.cpp

devices.o: devices.cpp devices.h \
		cameravideocapture.h \
		ui_devices.h \
		adddevice.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o devices.o devices.cpp

editmandatorygroup.o: editmandatorygroup.cpp editmandatorygroup.h \
		ui_editmandatorygroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o editmandatorygroup.o editmandatorygroup.cpp

eventlog.o: eventlog.cpp eventlog.h \
		databaseconnection.h \
		sendalert.h \
		ui_eventlog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o eventlog.o eventlog.cpp

main.o: main.cpp buksanspy.h \
		accessmanager.h \
		users.h \
		createuser.h \
		checkstring.h \
		sendalert.h \
		mandatorygroups.h \
		editmandatorygroup.h \
		checkconnection.h \
		buksanviewfinder.h \
		cameravideocapture.h \
		authorization.h \
		databaseconnection.h \
		buksanspyapp.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

buksanspy.o: buksanspy.cpp buksanspy.h \
		accessmanager.h \
		users.h \
		createuser.h \
		checkstring.h \
		sendalert.h \
		mandatorygroups.h \
		editmandatorygroup.h \
		checkconnection.h \
		buksanviewfinder.h \
		cameravideocapture.h \
		ui_buksanspy.h \
		adddevice.h \
		networkinfo.h \
		devices.h \
		eventlog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o buksanspy.o buksanspy.cpp

mandatorygroups.o: mandatorygroups.cpp mandatorygroups.h \
		accessmanager.h \
		editmandatorygroup.h \
		ui_mandatorygroups.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mandatorygroups.o mandatorygroups.cpp

mandatorymarkcreator.o: mandatorymarkcreator.cpp mandatorymarkcreator.h \
		ui_mandatorymarkcreator.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mandatorymarkcreator.o mandatorymarkcreator.cpp

mandatorymarkseditor.o: mandatorymarkseditor.cpp mandatorymarkseditor.h \
		ui_mandatorymarkseditor.h \
		mandatorymarkcreator.h \
		accessmanager.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mandatorymarkseditor.o mandatorymarkseditor.cpp

networkinfo.o: networkinfo.cpp networkinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o networkinfo.o networkinfo.cpp

sendalert.o: sendalert.cpp sendalert.h \
		networkinfo.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o sendalert.o sendalert.cpp

users.o: users.cpp users.h \
		createuser.h \
		checkstring.h \
		sendalert.h \
		accessmanager.h \
		ui_users.h \
		mandatorymarkseditor.h \
		mandatorygroups.h \
		editmandatorygroup.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o users.o users.cpp

moc_accessmanager.o: moc_accessmanager.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_accessmanager.o moc_accessmanager.cpp

moc_adddevice.o: moc_adddevice.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_adddevice.o moc_adddevice.cpp

moc_authorization.o: moc_authorization.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_authorization.o moc_authorization.cpp

moc_buksanspy.o: moc_buksanspy.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buksanspy.o moc_buksanspy.cpp

moc_buksanviewfinder.o: moc_buksanviewfinder.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_buksanviewfinder.o moc_buksanviewfinder.cpp

moc_cameravideocapture.o: moc_cameravideocapture.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_cameravideocapture.o moc_cameravideocapture.cpp

moc_checkconnection.o: moc_checkconnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_checkconnection.o moc_checkconnection.cpp

moc_checkstring.o: moc_checkstring.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_checkstring.o moc_checkstring.cpp

moc_createuser.o: moc_createuser.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_createuser.o moc_createuser.cpp

moc_databaseconnection.o: moc_databaseconnection.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_databaseconnection.o moc_databaseconnection.cpp

moc_datacryptor.o: moc_datacryptor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_datacryptor.o moc_datacryptor.cpp

moc_devices.o: moc_devices.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_devices.o moc_devices.cpp

moc_editmandatorygroup.o: moc_editmandatorygroup.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_editmandatorygroup.o moc_editmandatorygroup.cpp

moc_eventlog.o: moc_eventlog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_eventlog.o moc_eventlog.cpp

moc_mandatorygroups.o: moc_mandatorygroups.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mandatorygroups.o moc_mandatorygroups.cpp

moc_mandatorymarkcreator.o: moc_mandatorymarkcreator.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mandatorymarkcreator.o moc_mandatorymarkcreator.cpp

moc_mandatorymarkseditor.o: moc_mandatorymarkseditor.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mandatorymarkseditor.o moc_mandatorymarkseditor.cpp

moc_networkinfo.o: moc_networkinfo.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_networkinfo.o moc_networkinfo.cpp

moc_sendalert.o: moc_sendalert.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_sendalert.o moc_sendalert.cpp

moc_users.o: moc_users.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_users.o moc_users.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/BuksanSpy/bin || mkdir -p $(INSTALL_ROOT)/opt/BuksanSpy/bin
	$(QINSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/BuksanSpy/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/BuksanSpy/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/BuksanSpy/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

.SUFFIXES:

